### ISSUE TITLE
Recovering Probes causes Segfault

### ISSUE THREAD

**Issue by jdhirst** [EvEmu-Project/evemu_Crucible#170]
While testing my new code for Wormhole implementation, I noticed the following every time I try to recovery any amount of probes:
```
Thread 1 "eve-server" received signal SIGSEGV, Segmentation fault.
0x00007ffff7de0e03 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) () from /lib64/libstdc++.so.6
Missing separate debuginfos, use: dnf debuginfo-install boost-system-1.73.0-10.fc33.x86_64 glibc-2.32-10.fc33.x86_64 libgcc-10.3.1-1.fc33.x86_64 libstdc++-10.3.1-1.fc33.x86_64 mariadb-connector-c-3.1.13-1.fc33.x86_64 openssl-libs-1.1.1l-2.fc33.x86_64
(gdb) bt
#0  0x00007ffff7de0e03 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) () from /lib64/libstdc++.so.6
#1  0x0000000000ad9693 in std::_Rb_tree_iterator<std::pair<unsigned int const, ProbeSE*> >::operator++ (this=0x7fffffffc990)
    at /usr/include/c++/10/bits/stl_tree.h:287
#2  0x0000000000adb860 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, ProbeSE*>, std::_Select1st<std::pair<unsigned int const, ProbeSE*> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, ProbeSE*> > >::erase[abi:cxx11](std::_Rb_tree_iterator<std::pair<unsigned int const, ProbeSE*> >) (this=0x163c6d0, __position=
    {first = 1667331187, second = 0x9750065}) at /usr/include/c++/10/bits/stl_tree.h:1217
#3  0x0000000000ad96c3 in std::map<unsigned int, ProbeSE*, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, ProbeSE*> > >::erase[abi:cxx11](std::_Rb_tree_iterator<std::pair<unsigned int const, ProbeSE*> >) (this=0x163c6d0, __position=
  {first = 1667331187, second = 0x9750065}) at /usr/include/c++/10/bits/stl_map.h:1038
#4  0x0000000000ad41a7 in EntityList::Process (this=0x163c540) at /home/fedora/server/src/eve-server/EntityList.cpp:215
#5  0x0000000000a960ae in main (argc=1, argv=0x7fffffffe398) at /home/fedora/server/src/eve-server/eve-server.cpp:905
```

**Comment by zhyrohaad** [comment]
probe scanning code was complete at one time (circa late 2018), including probe retrieval.
currently, i cannot test due to other errors with my installation
i am thinking this may be just a fluke...

**Comment by mcp77** [comment]
It's still an issue. Could someone remove the testlabel?
